[2018-04-23 10:50:42] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modx.class.php : 697) PHP warning: Invalid argument supplied for foreach()
[2018-04-23 10:50:42] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modx.class.php : 697) PHP warning: Invalid argument supplied for foreach()
[2018-04-23 10:53:02] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modx.class.php : 697) PHP warning: Invalid argument supplied for foreach()
[2018-04-23 10:53:02] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modx.class.php : 697) PHP warning: Invalid argument supplied for foreach()
[2018-04-23 11:04:06] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/transport/modtransportpackage.class.php : 384) Невозможно открыть файл для чтения: http://modx.s3.amazonaws.com/extras/4d556c62b2b083396d000b9c/formit-4.0.0-pl.transport.zip?revolution_version=Revolution-2.6.3-pl
[2018-04-23 11:33:56] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 394) Error caching action map mgr/actions
[2018-04-23 11:38:59] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 394) Error caching action map mgr/actions
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modExtensionPackage`.`id`, `modExtensionPackage`.`namespace`, `modExtensionPackage`.`name`, `modExtensionPackage`.`path`, `modExtensionPackage`.`table_prefix`, `modExtensionPackage`.`service_class`, `modExtensionPackage`.`service_name`, `modExtensionPackage`.`created_at`, `modExtensionPackage`.`updated_at`, Namespace.path AS namespace_path FROM `ewal_extension_packages` AS `modExtensionPackage` JOIN `ewal_namespaces` `Namespace` ON `modExtensionPackage`.`namespace` =  `Namespace`.`name` ORDER BY namespace ASC 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modExtensionPackage`.`id`, `modExtensionPackage`.`namespace`, `modExtensionPackage`.`name`, `modExtensionPackage`.`path`, `modExtensionPackage`.`table_prefix`, `modExtensionPackage`.`service_class`, `modExtensionPackage`.`service_name`, `modExtensionPackage`.`created_at`, `modExtensionPackage`.`updated_at`, Namespace.path AS namespace_path FROM `ewal_extension_packages` AS `modExtensionPackage` JOIN `ewal_namespaces` `Namespace` ON `modExtensionPackage`.`namespace` =  `Namespace`.`name` ORDER BY namespace ASC 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:53] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modExtensionPackage`.`id`, `modExtensionPackage`.`namespace`, `modExtensionPackage`.`name`, `modExtensionPackage`.`path`, `modExtensionPackage`.`table_prefix`, `modExtensionPackage`.`service_class`, `modExtensionPackage`.`service_name`, `modExtensionPackage`.`created_at`, `modExtensionPackage`.`updated_at`, Namespace.path AS namespace_path FROM `ewal_extension_packages` AS `modExtensionPackage` JOIN `ewal_namespaces` `Namespace` ON `modExtensionPackage`.`namespace` =  `Namespace`.`name` ORDER BY namespace ASC 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modExtensionPackage`.`id`, `modExtensionPackage`.`namespace`, `modExtensionPackage`.`name`, `modExtensionPackage`.`path`, `modExtensionPackage`.`table_prefix`, `modExtensionPackage`.`service_class`, `modExtensionPackage`.`service_name`, `modExtensionPackage`.`created_at`, `modExtensionPackage`.`updated_at`, Namespace.path AS namespace_path FROM `ewal_extension_packages` AS `modExtensionPackage` JOIN `ewal_namespaces` `Namespace` ON `modExtensionPackage`.`namespace` =  `Namespace`.`name` ORDER BY namespace ASC 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:32:54] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modExtensionPackage`.`id`, `modExtensionPackage`.`namespace`, `modExtensionPackage`.`name`, `modExtensionPackage`.`path`, `modExtensionPackage`.`table_prefix`, `modExtensionPackage`.`service_class`, `modExtensionPackage`.`service_name`, `modExtensionPackage`.`created_at`, `modExtensionPackage`.`updated_at`, Namespace.path AS namespace_path FROM `ewal_extension_packages` AS `modExtensionPackage` JOIN `ewal_namespaces` `Namespace` ON `modExtensionPackage`.`namespace` =  `Namespace`.`name` ORDER BY namespace ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT DISTINCT `language` FROM `ewal_lexicon_entries` AS `modLexiconEntry` WHERE  ( `modLexiconEntry`.`namespace` = ? AND `modLexiconEntry`.`language` NOT IN (,,,,,,,,,,,,,,,,,,,,,,,,,,,,,) )  
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modActionDom`.`id`, `modActionDom`.`set`, `modActionDom`.`action`, `modActionDom`.`name`, `modActionDom`.`description`, `modActionDom`.`xtype`, `modActionDom`.`container`, `modActionDom`.`rule`, `modActionDom`.`value`, `modActionDom`.`constraint`, `modActionDom`.`constraint_field`, `modActionDom`.`constraint_class`, `modActionDom`.`active`, `modActionDom`.`for_parent`, `modActionDom`.`rank`, `FCSet`.`constraint_class`, `FCSet`.`constraint_field`, `FCSet`.`constraint`, `FCSet`.`template` FROM `ewal_actiondom` AS `modActionDom` JOIN `ewal_fc_sets` `FCSet` ON `modActionDom`.`set` =  `FCSet`.`id` JOIN `ewal_fc_profiles` `Profile` ON FCSet.profile = Profile.id LEFT JOIN `ewal_fc_profiles_usergroups` `ProfileUserGroup` ON Profile.id = ProfileUserGroup.profile LEFT JOIN `ewal_fc_profiles` `UGProfile` ON UGProfile.id = ProfileUserGroup.profile WHERE  ( `modActionDom`.`action` = ? AND `modActionDom`.`for_parent` = ? AND `FCSet`.`active` = ? AND `Profile`.`active` = ? )  ORDER BY modActionDom.rank ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modActionDom`.`id`, `modActionDom`.`set`, `modActionDom`.`action`, `modActionDom`.`name`, `modActionDom`.`description`, `modActionDom`.`xtype`, `modActionDom`.`container`, `modActionDom`.`rule`, `modActionDom`.`value`, `modActionDom`.`constraint`, `modActionDom`.`constraint_field`, `modActionDom`.`constraint_class`, `modActionDom`.`active`, `modActionDom`.`for_parent`, `modActionDom`.`rank`, `FCSet`.`constraint_class`, `FCSet`.`constraint_field`, `FCSet`.`constraint`, `FCSet`.`template` FROM `ewal_actiondom` AS `modActionDom` JOIN `ewal_fc_sets` `FCSet` ON `modActionDom`.`set` =  `FCSet`.`id` JOIN `ewal_fc_profiles` `Profile` ON FCSet.profile = Profile.id LEFT JOIN `ewal_fc_profiles_usergroups` `ProfileUserGroup` ON Profile.id = ProfileUserGroup.profile LEFT JOIN `ewal_fc_profiles` `UGProfile` ON UGProfile.id = ProfileUserGroup.profile WHERE  ( `modActionDom`.`action` = ? AND `modActionDom`.`for_parent` = ? AND `FCSet`.`active` = ? AND `Profile`.`active` = ? )  ORDER BY modActionDom.rank ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modNamespace`.`name` AS `modNamespace_name`, `modNamespace`.`path` AS `modNamespace_path`, `modNamespace`.`assets_path` AS `modNamespace_assets_path` FROM `ewal_namespaces` AS `modNamespace` WHERE `modNamespace`.`name` = ? 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modNamespace`.`name` AS `modNamespace_name`, `modNamespace`.`path` AS `modNamespace_path`, `modNamespace`.`assets_path` AS `modNamespace_assets_path` FROM `ewal_namespaces` AS `modNamespace` WHERE `modNamespace`.`name` = ?  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modNamespace`.`name` AS `modNamespace_name`, `modNamespace`.`path` AS `modNamespace_path`, `modNamespace`.`assets_path` AS `modNamespace_assets_path` FROM `ewal_namespaces` AS `modNamespace` WHERE `modNamespace`.`name` = ? 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modNamespace`.`name` AS `modNamespace_name`, `modNamespace`.`path` AS `modNamespace_path`, `modNamespace`.`assets_path` AS `modNamespace_assets_path` FROM `ewal_namespaces` AS `modNamespace` WHERE `modNamespace`.`name` = ?  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modLexiconEntry`.`id` AS `modLexiconEntry_id`, `modLexiconEntry`.`name` AS `modLexiconEntry_name`, `modLexiconEntry`.`value` AS `modLexiconEntry_value`, `modLexiconEntry`.`topic` AS `modLexiconEntry_topic`, `modLexiconEntry`.`namespace` AS `modLexiconEntry_namespace`, `modLexiconEntry`.`language` AS `modLexiconEntry_language`, `modLexiconEntry`.`createdon` AS `modLexiconEntry_createdon`, `modLexiconEntry`.`editedon` AS `modLexiconEntry_editedon` FROM `ewal_lexicon_entries` AS `modLexiconEntry` JOIN `ewal_namespaces` `Namespace` ON `modLexiconEntry`.`namespace` =  `Namespace`.`name` WHERE  ( `modLexiconEntry`.`topic` = ? AND `modLexiconEntry`.`language` = ? AND `Namespace`.`name` = ? )  ORDER BY `modLexiconEntry`.`name` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modExtensionPackage`.`id`, `modExtensionPackage`.`namespace`, `modExtensionPackage`.`name`, `modExtensionPackage`.`path`, `modExtensionPackage`.`table_prefix`, `modExtensionPackage`.`service_class`, `modExtensionPackage`.`service_name`, `modExtensionPackage`.`created_at`, `modExtensionPackage`.`updated_at`, Namespace.path AS namespace_path FROM `ewal_extension_packages` AS `modExtensionPackage` JOIN `ewal_namespaces` `Namespace` ON `modExtensionPackage`.`namespace` =  `Namespace`.`name` ORDER BY namespace ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `id` FROM `ewal_site_content` AS `modResource` WHERE  ( `modResource`.`context_key` = ? AND `modResource`.`uri` = ? AND `modResource`.`deleted` = ? )  
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modChunk`.`id` AS `modChunk_id`, `modChunk`.`source` AS `modChunk_source`, `modChunk`.`property_preprocess` AS `modChunk_property_preprocess`, `modChunk`.`name` AS `modChunk_name`, `modChunk`.`description` AS `modChunk_description`, `modChunk`.`editor_type` AS `modChunk_editor_type`, `modChunk`.`category` AS `modChunk_category`, `modChunk`.`cache_type` AS `modChunk_cache_type`, `modChunk`.`snippet` AS `modChunk_snippet`, `modChunk`.`locked` AS `modChunk_locked`, `modChunk`.`properties` AS `modChunk_properties`, `modChunk`.`static` AS `modChunk_static`, `modChunk`.`static_file` AS `modChunk_static_file`, `Source`.`id` AS `Source_id`, `Source`.`name` AS `Source_name`, `Source`.`description` AS `Source_description`, `Source`.`class_key` AS `Source_class_key`, `Source`.`properties` AS `Source_properties`, `Source`.`is_stream` AS `Source_is_stream` FROM `ewal_site_htmlsnippets` AS `modChunk` LEFT JOIN `ewal_media_sources` `Source` ON `modChunk`.`source` = `Source`.`id` WHERE `modChunk`.`name` = ? ORDER BY `modChunk`.`id` ASC  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:37] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modExtensionPackage`.`id`, `modExtensionPackage`.`namespace`, `modExtensionPackage`.`name`, `modExtensionPackage`.`path`, `modExtensionPackage`.`table_prefix`, `modExtensionPackage`.`service_class`, `modExtensionPackage`.`service_name`, `modExtensionPackage`.`created_at`, `modExtensionPackage`.`updated_at`, Namespace.path AS namespace_path FROM `ewal_extension_packages` AS `modExtensionPackage` JOIN `ewal_namespaces` `Namespace` ON `modExtensionPackage`.`namespace` =  `Namespace`.`name` ORDER BY namespace ASC 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT DISTINCT `language` FROM `ewal_lexicon_entries` AS `modLexiconEntry` WHERE  ( `modLexiconEntry`.`namespace` = ? AND `modLexiconEntry`.`language` NOT IN (,,,,,,,,,,,,,,,,,,,,,,,,,,,,,) )  
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modActionDom`.`id`, `modActionDom`.`set`, `modActionDom`.`action`, `modActionDom`.`name`, `modActionDom`.`description`, `modActionDom`.`xtype`, `modActionDom`.`container`, `modActionDom`.`rule`, `modActionDom`.`value`, `modActionDom`.`constraint`, `modActionDom`.`constraint_field`, `modActionDom`.`constraint_class`, `modActionDom`.`active`, `modActionDom`.`for_parent`, `modActionDom`.`rank`, `FCSet`.`constraint_class`, `FCSet`.`constraint_field`, `FCSet`.`constraint`, `FCSet`.`template` FROM `ewal_actiondom` AS `modActionDom` JOIN `ewal_fc_sets` `FCSet` ON `modActionDom`.`set` =  `FCSet`.`id` JOIN `ewal_fc_profiles` `Profile` ON FCSet.profile = Profile.id LEFT JOIN `ewal_fc_profiles_usergroups` `ProfileUserGroup` ON Profile.id = ProfileUserGroup.profile LEFT JOIN `ewal_fc_profiles` `UGProfile` ON UGProfile.id = ProfileUserGroup.profile WHERE  ( `modActionDom`.`action` = ? AND `modActionDom`.`for_parent` = ? AND `FCSet`.`active` = ? AND `Profile`.`active` = ? )  ORDER BY modActionDom.rank ASC 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modActionDom`.`id`, `modActionDom`.`set`, `modActionDom`.`action`, `modActionDom`.`name`, `modActionDom`.`description`, `modActionDom`.`xtype`, `modActionDom`.`container`, `modActionDom`.`rule`, `modActionDom`.`value`, `modActionDom`.`constraint`, `modActionDom`.`constraint_field`, `modActionDom`.`constraint_class`, `modActionDom`.`active`, `modActionDom`.`for_parent`, `modActionDom`.`rank`, `FCSet`.`constraint_class`, `FCSet`.`constraint_field`, `FCSet`.`constraint`, `FCSet`.`template` FROM `ewal_actiondom` AS `modActionDom` JOIN `ewal_fc_sets` `FCSet` ON `modActionDom`.`set` =  `FCSet`.`id` JOIN `ewal_fc_profiles` `Profile` ON FCSet.profile = Profile.id LEFT JOIN `ewal_fc_profiles_usergroups` `ProfileUserGroup` ON Profile.id = ProfileUserGroup.profile LEFT JOIN `ewal_fc_profiles` `UGProfile` ON UGProfile.id = ProfileUserGroup.profile WHERE  ( `modActionDom`.`action` = ? AND `modActionDom`.`for_parent` = ? AND `FCSet`.`active` = ? AND `Profile`.`active` = ? )  ORDER BY modActionDom.rank ASC  - 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modUser`.`id` AS `modUser_id`, `modUser`.`username` AS `modUser_username`, `modUser`.`password` AS `modUser_password`, `modUser`.`cachepwd` AS `modUser_cachepwd`, `modUser`.`class_key` AS `modUser_class_key`, `modUser`.`active` AS `modUser_active`, `modUser`.`remote_key` AS `modUser_remote_key`, `modUser`.`remote_data` AS `modUser_remote_data`, `modUser`.`hash_class` AS `modUser_hash_class`, `modUser`.`salt` AS `modUser_salt`, `modUser`.`primary_group` AS `modUser_primary_group`, `modUser`.`session_stale` AS `modUser_session_stale`, `modUser`.`sudo` AS `modUser_sudo`, `modUser`.`createdon` AS `modUser_createdon` FROM `ewal_users` AS `modUser` WHERE `modUser`.`username` = ? 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modUser`.`id` AS `modUser_id`, `modUser`.`username` AS `modUser_username`, `modUser`.`password` AS `modUser_password`, `modUser`.`cachepwd` AS `modUser_cachepwd`, `modUser`.`class_key` AS `modUser_class_key`, `modUser`.`active` AS `modUser_active`, `modUser`.`remote_key` AS `modUser_remote_key`, `modUser`.`remote_data` AS `modUser_remote_data`, `modUser`.`hash_class` AS `modUser_hash_class`, `modUser`.`salt` AS `modUser_salt`, `modUser`.`primary_group` AS `modUser_primary_group`, `modUser`.`session_stale` AS `modUser_session_stale`, `modUser`.`sudo` AS `modUser_sudo`, `modUser`.`createdon` AS `modUser_createdon` FROM `ewal_users` AS `modUser` WHERE `modUser`.`username` = ?  - 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modUser`.`id` AS `modUser_id`, `modUser`.`username` AS `modUser_username`, `modUser`.`password` AS `modUser_password`, `modUser`.`cachepwd` AS `modUser_cachepwd`, `modUser`.`class_key` AS `modUser_class_key`, `modUser`.`active` AS `modUser_active`, `modUser`.`remote_key` AS `modUser_remote_key`, `modUser`.`remote_data` AS `modUser_remote_data`, `modUser`.`hash_class` AS `modUser_hash_class`, `modUser`.`salt` AS `modUser_salt`, `modUser`.`primary_group` AS `modUser_primary_group`, `modUser`.`session_stale` AS `modUser_session_stale`, `modUser`.`sudo` AS `modUser_sudo`, `modUser`.`createdon` AS `modUser_createdon`, `Profile`.`id` AS `Profile_id`, `Profile`.`internalKey` AS `Profile_internalKey`, `Profile`.`fullname` AS `Profile_fullname`, `Profile`.`email` AS `Profile_email`, `Profile`.`phone` AS `Profile_phone`, `Profile`.`mobilephone` AS `Profile_mobilephone`, `Profile`.`blocked` AS `Profile_blocked`, `Profile`.`blockeduntil` AS `Profile_blockeduntil`, `Profile`.`blockedafter` AS `Profile_blockedafter`, `Profile`.`logincount` AS `Profile_logincount`, `Profile`.`lastlogin` AS `Profile_lastlogin`, `Profile`.`thislogin` AS `Profile_thislogin`, `Profile`.`failedlogincount` AS `Profile_failedlogincount`, `Profile`.`sessionid` AS `Profile_sessionid`, `Profile`.`dob` AS `Profile_dob`, `Profile`.`gender` AS `Profile_gender`, `Profile`.`address` AS `Profile_address`, `Profile`.`country` AS `Profile_country`, `Profile`.`city` AS `Profile_city`, `Profile`.`state` AS `Profile_state`, `Profile`.`zip` AS `Profile_zip`, `Profile`.`fax` AS `Profile_fax`, `Profile`.`photo` AS `Profile_photo`, `Profile`.`comment` AS `Profile_comment`, `Profile`.`website` AS `Profile_website`, `Profile`.`extended` AS `Profile_extended`, `UserSettings`.`user` AS `UserSettings_user`, `UserSettings`.`key` AS `UserSettings_key`, `UserSettings`.`value` AS `UserSettings_value`, `UserSettings`.`xtype` AS `UserSettings_xtype`, `UserSettings`.`namespace` AS `UserSettings_namespace`, `UserSettings`.`area` AS `UserSettings_area`, `UserSettings`.`editedon` AS `UserSettings_editedon` FROM `ewal_users` AS `modUser` LEFT JOIN `ewal_user_attributes` `Profile` ON `modUser`.`id` = `Profile`.`internalKey` LEFT JOIN `ewal_user_settings` `UserSettings` ON `modUser`.`id` = `UserSettings`.`user` WHERE `modUser`.`username` = ? ORDER BY `modUser`.`id` ASC 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modUser`.`id` AS `modUser_id`, `modUser`.`username` AS `modUser_username`, `modUser`.`password` AS `modUser_password`, `modUser`.`cachepwd` AS `modUser_cachepwd`, `modUser`.`class_key` AS `modUser_class_key`, `modUser`.`active` AS `modUser_active`, `modUser`.`remote_key` AS `modUser_remote_key`, `modUser`.`remote_data` AS `modUser_remote_data`, `modUser`.`hash_class` AS `modUser_hash_class`, `modUser`.`salt` AS `modUser_salt`, `modUser`.`primary_group` AS `modUser_primary_group`, `modUser`.`session_stale` AS `modUser_session_stale`, `modUser`.`sudo` AS `modUser_sudo`, `modUser`.`createdon` AS `modUser_createdon`, `Profile`.`id` AS `Profile_id`, `Profile`.`internalKey` AS `Profile_internalKey`, `Profile`.`fullname` AS `Profile_fullname`, `Profile`.`email` AS `Profile_email`, `Profile`.`phone` AS `Profile_phone`, `Profile`.`mobilephone` AS `Profile_mobilephone`, `Profile`.`blocked` AS `Profile_blocked`, `Profile`.`blockeduntil` AS `Profile_blockeduntil`, `Profile`.`blockedafter` AS `Profile_blockedafter`, `Profile`.`logincount` AS `Profile_logincount`, `Profile`.`lastlogin` AS `Profile_lastlogin`, `Profile`.`thislogin` AS `Profile_thislogin`, `Profile`.`failedlogincount` AS `Profile_failedlogincount`, `Profile`.`sessionid` AS `Profile_sessionid`, `Profile`.`dob` AS `Profile_dob`, `Profile`.`gender` AS `Profile_gender`, `Profile`.`address` AS `Profile_address`, `Profile`.`country` AS `Profile_country`, `Profile`.`city` AS `Profile_city`, `Profile`.`state` AS `Profile_state`, `Profile`.`zip` AS `Profile_zip`, `Profile`.`fax` AS `Profile_fax`, `Profile`.`photo` AS `Profile_photo`, `Profile`.`comment` AS `Profile_comment`, `Profile`.`website` AS `Profile_website`, `Profile`.`extended` AS `Profile_extended`, `UserSettings`.`user` AS `UserSettings_user`, `UserSettings`.`key` AS `UserSettings_key`, `UserSettings`.`value` AS `UserSettings_value`, `UserSettings`.`xtype` AS `UserSettings_xtype`, `UserSettings`.`namespace` AS `UserSettings_namespace`, `UserSettings`.`area` AS `UserSettings_area`, `UserSettings`.`editedon` AS `UserSettings_editedon` FROM `ewal_users` AS `modUser` LEFT JOIN `ewal_user_attributes` `Profile` ON `modUser`.`id` = `Profile`.`internalKey` LEFT JOIN `ewal_user_settings` `UserSettings` ON `modUser`.`id` = `UserSettings`.`user` WHERE `modUser`.`username` = ? ORDER BY `modUser`.`id` ASC  - 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:39] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modExtensionPackage`.`id`, `modExtensionPackage`.`namespace`, `modExtensionPackage`.`name`, `modExtensionPackage`.`path`, `modExtensionPackage`.`table_prefix`, `modExtensionPackage`.`service_class`, `modExtensionPackage`.`service_name`, `modExtensionPackage`.`created_at`, `modExtensionPackage`.`updated_at`, Namespace.path AS namespace_path FROM `ewal_extension_packages` AS `modExtensionPackage` JOIN `ewal_namespaces` `Namespace` ON `modExtensionPackage`.`namespace` =  `Namespace`.`name` ORDER BY namespace ASC 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT DISTINCT `language` FROM `ewal_lexicon_entries` AS `modLexiconEntry` WHERE  ( `modLexiconEntry`.`namespace` = ? AND `modLexiconEntry`.`language` NOT IN (,,,,,,,,,,,,,,,,,,,,,,,,,,,,,) )  
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modActionDom`.`id`, `modActionDom`.`set`, `modActionDom`.`action`, `modActionDom`.`name`, `modActionDom`.`description`, `modActionDom`.`xtype`, `modActionDom`.`container`, `modActionDom`.`rule`, `modActionDom`.`value`, `modActionDom`.`constraint`, `modActionDom`.`constraint_field`, `modActionDom`.`constraint_class`, `modActionDom`.`active`, `modActionDom`.`for_parent`, `modActionDom`.`rank`, `FCSet`.`constraint_class`, `FCSet`.`constraint_field`, `FCSet`.`constraint`, `FCSet`.`template` FROM `ewal_actiondom` AS `modActionDom` JOIN `ewal_fc_sets` `FCSet` ON `modActionDom`.`set` =  `FCSet`.`id` JOIN `ewal_fc_profiles` `Profile` ON FCSet.profile = Profile.id LEFT JOIN `ewal_fc_profiles_usergroups` `ProfileUserGroup` ON Profile.id = ProfileUserGroup.profile LEFT JOIN `ewal_fc_profiles` `UGProfile` ON UGProfile.id = ProfileUserGroup.profile WHERE  ( `modActionDom`.`action` = ? AND `modActionDom`.`for_parent` = ? AND `FCSet`.`active` = ? AND `Profile`.`active` = ? )  ORDER BY modActionDom.rank ASC 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modActionDom`.`id`, `modActionDom`.`set`, `modActionDom`.`action`, `modActionDom`.`name`, `modActionDom`.`description`, `modActionDom`.`xtype`, `modActionDom`.`container`, `modActionDom`.`rule`, `modActionDom`.`value`, `modActionDom`.`constraint`, `modActionDom`.`constraint_field`, `modActionDom`.`constraint_class`, `modActionDom`.`active`, `modActionDom`.`for_parent`, `modActionDom`.`rank`, `FCSet`.`constraint_class`, `FCSet`.`constraint_field`, `FCSet`.`constraint`, `FCSet`.`template` FROM `ewal_actiondom` AS `modActionDom` JOIN `ewal_fc_sets` `FCSet` ON `modActionDom`.`set` =  `FCSet`.`id` JOIN `ewal_fc_profiles` `Profile` ON FCSet.profile = Profile.id LEFT JOIN `ewal_fc_profiles_usergroups` `ProfileUserGroup` ON Profile.id = ProfileUserGroup.profile LEFT JOIN `ewal_fc_profiles` `UGProfile` ON UGProfile.id = ProfileUserGroup.profile WHERE  ( `modActionDom`.`action` = ? AND `modActionDom`.`for_parent` = ? AND `FCSet`.`active` = ? AND `Profile`.`active` = ? )  ORDER BY modActionDom.rank ASC  - 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modUser`.`id` AS `modUser_id`, `modUser`.`username` AS `modUser_username`, `modUser`.`password` AS `modUser_password`, `modUser`.`cachepwd` AS `modUser_cachepwd`, `modUser`.`class_key` AS `modUser_class_key`, `modUser`.`active` AS `modUser_active`, `modUser`.`remote_key` AS `modUser_remote_key`, `modUser`.`remote_data` AS `modUser_remote_data`, `modUser`.`hash_class` AS `modUser_hash_class`, `modUser`.`salt` AS `modUser_salt`, `modUser`.`primary_group` AS `modUser_primary_group`, `modUser`.`session_stale` AS `modUser_session_stale`, `modUser`.`sudo` AS `modUser_sudo`, `modUser`.`createdon` AS `modUser_createdon` FROM `ewal_users` AS `modUser` WHERE `modUser`.`username` = ? 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modUser`.`id` AS `modUser_id`, `modUser`.`username` AS `modUser_username`, `modUser`.`password` AS `modUser_password`, `modUser`.`cachepwd` AS `modUser_cachepwd`, `modUser`.`class_key` AS `modUser_class_key`, `modUser`.`active` AS `modUser_active`, `modUser`.`remote_key` AS `modUser_remote_key`, `modUser`.`remote_data` AS `modUser_remote_data`, `modUser`.`hash_class` AS `modUser_hash_class`, `modUser`.`salt` AS `modUser_salt`, `modUser`.`primary_group` AS `modUser_primary_group`, `modUser`.`session_stale` AS `modUser_session_stale`, `modUser`.`sudo` AS `modUser_sudo`, `modUser`.`createdon` AS `modUser_createdon` FROM `ewal_users` AS `modUser` WHERE `modUser`.`username` = ?  - 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modUser`.`id` AS `modUser_id`, `modUser`.`username` AS `modUser_username`, `modUser`.`password` AS `modUser_password`, `modUser`.`cachepwd` AS `modUser_cachepwd`, `modUser`.`class_key` AS `modUser_class_key`, `modUser`.`active` AS `modUser_active`, `modUser`.`remote_key` AS `modUser_remote_key`, `modUser`.`remote_data` AS `modUser_remote_data`, `modUser`.`hash_class` AS `modUser_hash_class`, `modUser`.`salt` AS `modUser_salt`, `modUser`.`primary_group` AS `modUser_primary_group`, `modUser`.`session_stale` AS `modUser_session_stale`, `modUser`.`sudo` AS `modUser_sudo`, `modUser`.`createdon` AS `modUser_createdon`, `Profile`.`id` AS `Profile_id`, `Profile`.`internalKey` AS `Profile_internalKey`, `Profile`.`fullname` AS `Profile_fullname`, `Profile`.`email` AS `Profile_email`, `Profile`.`phone` AS `Profile_phone`, `Profile`.`mobilephone` AS `Profile_mobilephone`, `Profile`.`blocked` AS `Profile_blocked`, `Profile`.`blockeduntil` AS `Profile_blockeduntil`, `Profile`.`blockedafter` AS `Profile_blockedafter`, `Profile`.`logincount` AS `Profile_logincount`, `Profile`.`lastlogin` AS `Profile_lastlogin`, `Profile`.`thislogin` AS `Profile_thislogin`, `Profile`.`failedlogincount` AS `Profile_failedlogincount`, `Profile`.`sessionid` AS `Profile_sessionid`, `Profile`.`dob` AS `Profile_dob`, `Profile`.`gender` AS `Profile_gender`, `Profile`.`address` AS `Profile_address`, `Profile`.`country` AS `Profile_country`, `Profile`.`city` AS `Profile_city`, `Profile`.`state` AS `Profile_state`, `Profile`.`zip` AS `Profile_zip`, `Profile`.`fax` AS `Profile_fax`, `Profile`.`photo` AS `Profile_photo`, `Profile`.`comment` AS `Profile_comment`, `Profile`.`website` AS `Profile_website`, `Profile`.`extended` AS `Profile_extended`, `UserSettings`.`user` AS `UserSettings_user`, `UserSettings`.`key` AS `UserSettings_key`, `UserSettings`.`value` AS `UserSettings_value`, `UserSettings`.`xtype` AS `UserSettings_xtype`, `UserSettings`.`namespace` AS `UserSettings_namespace`, `UserSettings`.`area` AS `UserSettings_area`, `UserSettings`.`editedon` AS `UserSettings_editedon` FROM `ewal_users` AS `modUser` LEFT JOIN `ewal_user_attributes` `Profile` ON `modUser`.`id` = `Profile`.`internalKey` LEFT JOIN `ewal_user_settings` `UserSettings` ON `modUser`.`id` = `UserSettings`.`user` WHERE `modUser`.`username` = ? ORDER BY `modUser`.`id` ASC 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 546) Error  preparing statement: SELECT `modUser`.`id` AS `modUser_id`, `modUser`.`username` AS `modUser_username`, `modUser`.`password` AS `modUser_password`, `modUser`.`cachepwd` AS `modUser_cachepwd`, `modUser`.`class_key` AS `modUser_class_key`, `modUser`.`active` AS `modUser_active`, `modUser`.`remote_key` AS `modUser_remote_key`, `modUser`.`remote_data` AS `modUser_remote_data`, `modUser`.`hash_class` AS `modUser_hash_class`, `modUser`.`salt` AS `modUser_salt`, `modUser`.`primary_group` AS `modUser_primary_group`, `modUser`.`session_stale` AS `modUser_session_stale`, `modUser`.`sudo` AS `modUser_sudo`, `modUser`.`createdon` AS `modUser_createdon`, `Profile`.`id` AS `Profile_id`, `Profile`.`internalKey` AS `Profile_internalKey`, `Profile`.`fullname` AS `Profile_fullname`, `Profile`.`email` AS `Profile_email`, `Profile`.`phone` AS `Profile_phone`, `Profile`.`mobilephone` AS `Profile_mobilephone`, `Profile`.`blocked` AS `Profile_blocked`, `Profile`.`blockeduntil` AS `Profile_blockeduntil`, `Profile`.`blockedafter` AS `Profile_blockedafter`, `Profile`.`logincount` AS `Profile_logincount`, `Profile`.`lastlogin` AS `Profile_lastlogin`, `Profile`.`thislogin` AS `Profile_thislogin`, `Profile`.`failedlogincount` AS `Profile_failedlogincount`, `Profile`.`sessionid` AS `Profile_sessionid`, `Profile`.`dob` AS `Profile_dob`, `Profile`.`gender` AS `Profile_gender`, `Profile`.`address` AS `Profile_address`, `Profile`.`country` AS `Profile_country`, `Profile`.`city` AS `Profile_city`, `Profile`.`state` AS `Profile_state`, `Profile`.`zip` AS `Profile_zip`, `Profile`.`fax` AS `Profile_fax`, `Profile`.`photo` AS `Profile_photo`, `Profile`.`comment` AS `Profile_comment`, `Profile`.`website` AS `Profile_website`, `Profile`.`extended` AS `Profile_extended`, `UserSettings`.`user` AS `UserSettings_user`, `UserSettings`.`key` AS `UserSettings_key`, `UserSettings`.`value` AS `UserSettings_value`, `UserSettings`.`xtype` AS `UserSettings_xtype`, `UserSettings`.`namespace` AS `UserSettings_namespace`, `UserSettings`.`area` AS `UserSettings_area`, `UserSettings`.`editedon` AS `UserSettings_editedon` FROM `ewal_users` AS `modUser` LEFT JOIN `ewal_user_attributes` `Profile` ON `modUser`.`id` = `Profile`.`internalKey` LEFT JOIN `ewal_user_settings` `UserSettings` ON `modUser`.`id` = `UserSettings`.`user` WHERE `modUser`.`username` = ? ORDER BY `modUser`.`id` ASC  - 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 652) Could not construct or prepare query because it is invalid or could not connect: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ? 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 263) Error preparing statement for query: SELECT `modSession`.`id` AS `modSession_id`, `modSession`.`access` AS `modSession_access`, `modSession`.`data` AS `modSession_data` FROM `ewal_session` AS `modSession` WHERE `modSession`.`id` = ?  - 
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 17:38:47] (ERROR in xPDOConnection::connect @ /mnt/sdb1/quo-group/core/xpdo/xpdo.class.php : 3114) SQLSTATE[HY000] [1045] Access denied for user 'laval_root'@'localhost' (using password: YES)
[2018-04-23 18:06:35] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
[2018-04-23 18:06:45] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
[2018-04-23 18:17:35] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 394) Error caching action map mgr/actions
[2018-04-23 18:17:35] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
[2018-04-23 18:33:43] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/element
[2018-04-23 18:41:50] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
[2018-04-24 06:41:15] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoobject.class.php : 1452) Error 23000 executing statement:
INSERT INTO `ewal_session` (`id`, `access`, `data`) VALUES ('8mr11onsto51rtol4on77la002', 1524552075, 'modx.user.0.resourceGroups|a:1:{s:3:\"mgr\";a:0:{}}modx.user.0.attributes|a:1:{s:3:\"mgr\";a:5:{s:16:\"modAccessContext\";a:1:{s:3:\"web\";a:1:{i:0;a:3:{s:9:\"principal\";i:0;s:9:\"authority\";s:1:\"0\";s:6:\"policy\";a:1:{s:4:\"load\";b:1;}}}}s:22:\"modAccessResourceGroup\";a:0:{}s:17:\"modAccessCategory\";a:0:{}s:28:\"sources.modAccessMediaSource\";a:0:{}s:18:\"modAccessNamespace\";a:0:{}}}')
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '8mr11onsto51rtol4on77la002' for key 'PRIMARY'
)

[2018-04-24 08:15:39] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
[2018-04-24 08:54:08] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modx.class.php : 990) `[[+id]]` is not a valid integer and may not be passed to makeUrl()
[2018-04-24 08:54:08] (ERROR in resource 1 @ /mnt/sdb1/quo-group/core/model/modx/modparser.class.php : 1372) Bad link tag `[[~[[+id]]]]` encountered
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:00:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:01:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:17] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_par4162837c84b289c7c84643215855ea39_dat0.png
[2018-04-24 09:01:17] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:18] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_par4162837c84b289c7c84643215855ea39_dat0.png
[2018-04-24 09:01:18] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:19] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_par4162837c84b289c7c84643215855ea39_dat0.png
[2018-04-24 09:01:19] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:19] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:01:19] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:01:41] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:46] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:01:46] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:46] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par0ba78bb0326502335f8683fdf331013a_dat0.jpeg
[2018-04-24 09:01:46] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:01:46] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:01:46] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:02:03] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:02:44] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:02:49] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:02:52] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_par505a0ce8a21685a7f2c0113893cf7c29_dat0.png
[2018-04-24 09:02:52] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:03:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_par505a0ce8a21685a7f2c0113893cf7c29_dat0.png
[2018-04-24 09:03:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:03:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_par505a0ce8a21685a7f2c0113893cf7c29_dat0.png
[2018-04-24 09:03:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:03:02] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_par0ba78bb0326502335f8683fdf331013a_dat0.jpeg
[2018-04-24 09:03:02] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:05:57] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 394) Error caching action map mgr/actions
[2018-04-24 09:05:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_par0ba78bb0326502335f8683fdf331013a_dat0.jpeg
[2018-04-24 09:05:57] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srce3565f322da494636e18cb979598a2c0_pare23411d0821ae56bf50a1f79d182c074_dat0.png
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcfe93a8dd0e553f657605269a9796f484_parfe63e9239bc49e2fae6900079200047d_dat0.png
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb928deed32433bf9e4d65a0ece210da0_par95b375c8da2a9cd7edaa29d52e3cc91b_dat0.png
[2018-04-24 09:06:00] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:04] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_par505a0ce8a21685a7f2c0113893cf7c29_dat0.png
[2018-04-24 09:06:04] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:05] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_par4162837c84b289c7c84643215855ea39_dat0.png
[2018-04-24 09:06:05] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:07] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src6d80c8719498884f8369528b6113266f_par4162837c84b289c7c84643215855ea39_dat0.png
[2018-04-24 09:06:07] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:07] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_par505a0ce8a21685a7f2c0113893cf7c29_dat0.png
[2018-04-24 09:06:07] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:40] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__src55e9567bb73a3e5a3c4c8b7fa6e913be_par4162837c84b289c7c84643215855ea39_dat0.png
[2018-04-24 09:06:40] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:06:40] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 121) phpThumb was unable to generate a thumbnail for: /mnt/sdb1/quo-group/core/cache/phpthumb/quo-group.ru__srcb07c6c9210ba8f62cd3b55d399acf28b_par505a0ce8a21685a7f2c0113893cf7c29_dat0.png
[2018-04-24 09:06:40] (ERROR @ /mnt/sdb1/quo-group/core/model/phpthumb/modphpthumb.class.php : 133) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 618
[2018-04-24 09:29:46] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
[2018-04-24 09:32:29] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
[2018-04-24 09:36:13] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/element
[2018-04-24 09:41:01] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 394) Error caching action map mgr/actions
[2018-04-24 09:42:39] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/element
[2018-04-24 09:42:49] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/element
[2018-04-24 10:09:19] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
[2018-04-24 11:42:29] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:42:29] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:42:50] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:42:50] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:43:23] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:43:23] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '1' AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` =' at line 1
[2018-04-24 11:44:38] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:44:38] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= '1' AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` =' at line 1
[2018-04-24 11:46:19] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:46:19] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 11:46:23] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:46:23] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 11:46:37] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:46:37] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 11:46:59] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:46:59] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 11:47:26] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:47:26] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 11:47:36] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 394) Error caching action map mgr/actions
[2018-04-24 11:47:39] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42000: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= 1 AND `modResource`.`parent` IN (9,32,33,34) AND `modResource`.`published` = 1' at line 1
[2018-04-24 11:47:39] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 11:48:01] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'TVinoffcasetv.value.value' in 'where clause'
[2018-04-24 11:48:01] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 11:48:09] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 11:48:34] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv' in 'where clause'
[2018-04-24 11:48:42] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv' in 'where clause'
[2018-04-24 11:48:57] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv' in 'where clause'
[2018-04-24 11:53:17] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'TVinoffcasetv.value.value' in 'where clause'
[2018-04-24 11:53:17] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 11:54:23] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'TVinoffcasetv.value.value' in 'where clause'
[2018-04-24 11:54:23] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 11:54:38] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'TVinoffcasetv.value.value' in 'where clause'
[2018-04-24 11:54:38] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 11:55:07] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'TVinoffcasetv.value.value' in 'where clause'
[2018-04-24 11:55:07] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 11:55:16] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'TVinoffcasetv.value.value' in 'where clause'
[2018-04-24 12:24:27] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:24:57] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:25:39] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:26:52] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:27:36] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 12:29:21] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:30:30] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:33:02] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 12:37:51] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:37:51] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:39:21] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:39:21] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:40:04] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:40:04] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:40:15] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:40:15] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:41:14] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:42:52] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:47:58] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 12:48:15] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 12:50:54] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:51:52] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'modResource.inOffCaseTv' in 'where clause'
[2018-04-24 12:52:27] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 12:53:06] (ERROR @ /mnt/sdb1/quo-group/core/components/pdotools/model/pdotools/pdofetch.class.php : 172) [pdoTools] Error 42S22: Unknown column 'inOffCaseTv.value' in 'where clause'
[2018-04-24 12:53:56] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:53:56] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:54:40] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:54:40] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:54:58] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: "{``TVinoffcasetv`.`value``:`one`}"
[2018-04-24 12:54:58] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 12:55:17] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: '{``TVinoffcasetv`.`value``:`one`}'
[2018-04-24 12:55:17] (ERROR @ /mnt/sdb1/quo-group/core/xpdo/om/xpdoquery.class.php : 702) Error parsing condition with key 0: 
[2018-04-24 13:23:30] (ERROR @ /mnt/sdb1/quo-group/core/model/modx/modcachemanager.class.php : 344) Error caching lexicon topic lexicon/ru/core/resource
